name: Build and public docker image

on:
  push:
    branches: "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # run only when code is compiling and tests are passing
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: 将仓库名称转换为小写
        run: echo "OWNER_NAME=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV


      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          file: dockerfile
          platforms: linux/amd64
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/${{ env.OWNER_NAME }}/eunomia-template:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
